### ISSUE TITLE
Code uploading fails

### ISSUE THREAD

**Issue by suvodip1212** [sparkfun/SparkFun_LilyPad_Simblee#4]
We have produced some PCB's with simblee. However, the code uploading failed in some PCB's in spite of the fact that that the connections are ok. Here is the minimal circuit used.
![simblee_minimal](https://user-images.githubusercontent.com/27431612/33113968-a3561b02-cf80-11e7-91b1-302ba724457a.PNG). Any help in this regard would be appreciated.

**Comment by bboyho** [comment]
Hi,

I'm sorry for the delay in reply. I was closing some issues when I noticed this. I'm not exactly sure why the board fails upon uploading on your custom board. I faintly heard from someone in production about a possible special heating profile when reflowing the chip to the board. 

Unfortunately, the board has been retired from our catalog and the manufacturer of the IC has discontinued the chip.
